# Generated by Django 2.0.6 on 2019-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_siteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='useFullName',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='userPassword',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='isActive',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='roleName',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
