# Generated by Django 2.0.6 on 2019-09-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20190919_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('userFullName', models.CharField(default='', max_length=200, null=True)),
                ('userEmail', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(default='', max_length=200)),
                ('userMobile', models.BigIntegerField()),
                ('userImage', models.CharField(default='', max_length=200, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.UserRole')),
            ],
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='userPassword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
